name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Main Stats & Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shreejitverma
          template: classic
          base: header, activity, community, repositories, metadata
          filename: metrics.main.svg
          config_timezone: America/New_York
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
          plugin_languages_aliases: Jupyter Notebook:Python

      - name: Activity & Commit Frequency
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shreejitverma
          template: classic
          base: ""
          filename: metrics.activity.svg
          config_timezone: America/New_York
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Advanced Metrics & Engagement
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shreejitverma
          template: classic
          base: ""
          filename: metrics.advanced.svg
          config_timezone: America/New_York
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_types: followers, following
