name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Identity & Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shreejitverma
          template: classic
          base: header, metadata, repositories
          filename: metrics.main.svg
          config_timezone: America/New_York
          plugin_languages: yes
          plugin_languages_indepth: no
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
          plugin_languages_aliases: Jupyter Notebook:Python
          output_action: commit
          committer_branch: metrics

      - name: Download Streak Metrics
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin metrics
          git checkout metrics || git checkout -b metrics
          curl -L "https://streak-stats.demolab.com?user=shreejitverma&theme=dracula&hide_border=true&background=000000&ring=4fff67&currStreakLabel=4fff67" -o metrics.streak.svg
          git add metrics.streak.svg
          git commit -m "Update streak metrics" || echo "No changes to commit"
          git push origin metrics

      - name: Coding Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shreejitverma
          template: classic
          base: ""
          filename: metrics.habits.svg
          config_timezone: America/New_York
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          output_action: commit
          committer_branch: metrics

      - name: Activity Heatmap
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shreejitverma
          template: classic
          base: ""
          filename: metrics.activity.svg
          config_timezone: America/New_York
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          output_action: commit
          committer_branch: metrics

      - name: Community & Project Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shreejitverma
          template: classic
          base: ""
          filename: metrics.advanced.svg
          config_timezone: America/New_York
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_types: followers, following
          output_action: commit
          committer_branch: metrics
